Feat : Profile
ElvenTools/elven-tools-dapp pull request #12
Opened 2022-05-31 11:15 UTC by theejkb

> Button 'Profil' added in header (only for connected user)

> Display the address, herotag and nonce of the connected wallet.

> Display a random profil (can be improved by using the maiar profile if possible).

WIP : Display every NFT on the wallet.

2022-06-03 12:46 UTC, theejkb commented
![navbar](https://user-images.githubusercontent.com/45352533/171856643-f284a872-a372-4590-a5a6-1ddd613acc2c.png)
![profil](https://user-images.githubusercontent.com/45352533/171856633-6dff2a46-0941-4ca0-adb3-e406ee6cd384.png)

2022-06-03 13:28 UTC, juliancwirko requested changes
You can remove the package-lock.json from the PR. If merged, I will update all that is required.

2022-06-03 13:28 UTC, juliancwirko commented on components/LoginModalButton.tsx
> +    window.location.href = '/';
this should probably use next router

2022-06-03 13:28 UTC, juliancwirko commented on components/User.tsx
> +      `https://api.elrond.com/accounts/${accountState.address}`
The API can't be hardcoded. There are env variables for that also, there are helpers for apiCalls in utils, and the dapp also uses SWR, which could be used here

2022-06-03 13:28 UTC, juliancwirko commented on components/User.tsx
> +          src="https://res.cloudinary.com/naaq/image/upload/v1653986673/t%C3%A9l%C3%A9chargement_aahft1.jpg"
Hardcoded avatar?

2022-06-03 13:28 UTC, juliancwirko commented on components/UserNft.tsx
> +      `https://api.elrond.com/accounts/${accountState.address}/nfts`
the same as above, hardcoded api and we can use swr here

2022-06-03 13:30 UTC, theejkb commented on components/User.tsx
> +          src="https://res.cloudinary.com/naaq/image/upload/v1653986673/t%C3%A9l%C3%A9chargement_aahft1.jpg"
I didn't found a way to get the profil image from Maiar App.

2022-06-03 13:32 UTC, theejkb commented
> You can remove the package-lock.json from the PR. If merged, I will update all that is required.

Done ✅

2022-06-03 13:35 UTC, juliancwirko commented on components/User.tsx
> +          src="https://res.cloudinary.com/naaq/image/upload/v1653986673/t%C3%A9l%C3%A9chargement_aahft1.jpg"
yes, so I think we should remove the functionality of avatar

2022-06-04 12:03 UTC, theejkb commented on components/User.tsx
> +          src="https://res.cloudinary.com/naaq/image/upload/v1653986673/t%C3%A9l%C3%A9chargement_aahft1.jpg"
Yep good idea

2022-11-26 19:37 UTC, juliancwirko commented
It will be implemented here: https://github.com/ElvenTools/elven-tools-dapp/pull/20
I will close this one.

2022-11-26 19:37 UTC, closed without merging